# Logos
logo: swc_logo.svg
logoAlt: Software Carpentry
logoFooter: logo-white.svg
logoFooterAlt: Software Carpentry

footer_overview_text: Software Carpentry is a lesson program of The Carpentries. Cake pastry candy carrot cake croissant tootsie roll chocolate bar dragée cotton candy.
